---

version: '3.1'

services:
  webserver:
    image: sudarko/simdondar:latest
    #pull_policy: always
    #build: https://github.com/sudarko/simdondar.git
    restart: always
    volumes:
    - upload:/var/www/upload
#    - /home/upload:/var/www/upload
    ports:
      - "8085:80"
    networks:
      - simdondar

  database:
    image: mysql:5.5
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - simdondar

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8086:80"
    networks:
      - simdondar

networks:
  simdondar:
volumes:
  upload:
  database:
